apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/shippingservice
images:
  - name: jukpozi/shippingservice
    newName: srepjcoreacr.azurecr.io/shippingservice
    newTag: 20f1ce3ea1c188a37672d3d330260d19d55c0883
