apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/shippingservice
images:
  - name: jukpozi/shippingservice
    newName: srepjcoreacr.azurecr.io/shippingservice
    newTag: da38b548fc7f2ec0b227fbf6985ea1da15589485
