apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/adservice
images:
  - name: jukpozi/adservice
    newName: srecoreacr.azurecr.io/adservice
    newTag: 23f6ba3ce3a219621dc69b30164d21383d2b2c27
