apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/adservice
images:
  - name: jukpozi/adservice
    newName: srepjcoreacr.azurecr.io/adservice
    newTag: 3f7b3380a3f9719aabe4a9a5ff99d493fb7f4312
