apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: "04361e26-d101-417d-b61a-b18b468cba61"
  labels:
    azure.workload.identity/use: "true"
