apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: "7cd1ff0c-20cd-45b0-acee-5e9f70760afa"
  labels:
    azure.workload.identity/use: "true"
