apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: "09ddd79b-1f43-439a-9956-ac8b25411023"
  labels:
    azure.workload.identity/use: "true"
