apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: shipping-worker-trigger-auth
  namespace: workers
spec:
  podIdentity:
    provider: azure-workload
    identityId: "04361e26-d101-417d-b61a-b18b468cba61"
