apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/frontend
images:
  - name: jukpozi/frontend
    newName: srepjcoreacr.azurecr.io/frontend
    newTag: 0453aa8d5a56a993dc322fea670cde56c9a98efd
