apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: "ea69c2e5-8ae6-4b17-8329-cda92d8aed4a"
  labels:
    azure.workload.identity/use: "true"
