apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: "98224623-cf71-439e-b480-d726de30d10e"
  labels:
    azure.workload.identity/use: "true"
