apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: "4debe7b5-d275-4bef-924c-9d3e5ce8adc9"
  labels:
    azure.workload.identity/use: "true"
