apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: "d0863138-07dd-41c5-bd94-a3a40f62e4be"
  labels:
    azure.workload.identity/use: "true"
