apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: "0744a964-44cb-470d-976c-0251afd3db83"
  labels:
    azure.workload.identity/use: "true"
