apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: "f9b73592-84d7-4b4a-b8b1-1cda01c4c6c3"
  labels:
    azure.workload.identity/use: "true"
