apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/currencyservice
images:
  - name: jukpozi/currencyservice
    newName: srepjcoreacr.azurecr.io/currencyservice
    newTag: 2bca2e4de8e831a76e2a7bacc046d3b1b69833b3
