apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cartservice
images:
  - name: jukpozi/cartservice
    newName: srecoreacr.azurecr.io/cartservice
    newTag: latest
