apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cartservice
images:
  - name: jukpozi/cartservice
    newName: srepjcoreacr.azurecr.io/cartservice
    newTag: ca29045831cf30e961432738a730cfe1e74ebfe7
