apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../workers/email-worker
images:
  - name: jukpozi/emailservice
    newName: srepjcoreacr.azurecr.io/emailservice
    newTag: 9900e3462ba62dc01ed41568f5ee75d19b9986e4
