apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/paymentservice
images:
  - name: jukpozi/paymentservice
    newName: srepjcoreacr.azurecr.io/paymentservice
    newTag: latest
