apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/emailservice
images:
  - name: jukpozi/emailservice
    newName: srepjcoreacr.azurecr.io/emailservice
    newTag: latest
