apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sre-platform

spec:
  project: default

  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: "2.19.0"
    helm:
      values: |
        podIdentity:
          azureWorkload:
            enabled: true
            clientId: "ba75ea83-4923-48a0-aa63-35b59053dfa9"
            tenantId: "104704fd-f711-4575-99d5-8a6588951c90"

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
