apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/checkoutservice
images:
  - name: jukpozi/checkoutservice
    newName: srecoreacr.azurecr.io/checkoutservice
    newTag: latest
