apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/loadgenerator
images:
  - name: jukpozi/loadgenerator
    newName: srepjcoreacr.azurecr.io/loadgenerator
    newTag: latest
