apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/recommendationservice
images:
  - name: jukpozi/recommendationservice
    newName: srepjcoreacr.azurecr.io/recommendationservice
    newTag: 5c5742d471377c9c26be00abeea5df1aa56480c2
