apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: "b023641f-3f8a-45b0-a768-81cd63548666"
  labels:
    azure.workload.identity/use: "true"
