apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: "d1e209a0-4c2a-4b79-8b40-4b42e4a459ef"
  labels:
    azure.workload.identity/use: "true"
