apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: payment-worker-trigger-auth
  namespace: workers
spec:
  podIdentity:
    provider: azure-workload
    identityId: "d1e209a0-4c2a-4b79-8b40-4b42e4a459ef"
