apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: "546eacdf-f31f-4950-9319-73a6ce56713c"
  labels:
    azure.workload.identity/use: "true"
