apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: "d82d4077-b940-4d78-9fcf-84b4b81044a0"
  labels:
    azure.workload.identity/use: "true"
