apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  namespace: core
  annotations:
    azure.workload.identity/client-id: "a0b14ac1-7db5-4199-97f2-4c887e30c800"
  labels:
    azure.workload.identity/use: "true"
