apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../workers/payment-worker
images:
  - name: jukpozi/paymentservice
    newName: srecoreacr.azurecr.io/paymentservice
    newTag: latest
