apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: "b3aa47bc-436c-4e94-a6ee-86bd4b3074bd"
  labels:
    azure.workload.identity/use: "true"
