apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: "05028a94-fa8a-4a16-81d2-fed67465f193"
  labels:
    azure.workload.identity/use: "true"
