apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice-worker-sa
  namespace: workers
  annotations:
    azure.workload.identity/client-id: "5128d644-0463-4e9d-bad8-fa2d26882f89"
  labels:
    azure.workload.identity/use: "true"
