apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: email-worker-trigger-auth
  namespace: workers
spec:
  podIdentity:
    provider: azure-workload
    identityId: "b3aa47bc-436c-4e94-a6ee-86bd4b3074bd"
