name: Build ShoppingAssistantService Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "services/shoppingassistantservice/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      security-events: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: services/shoppingassistantservice
        run: pip install -r requirements.txt pytest

      - name: Run tests
        working-directory: services/shoppingassistantservice
        run: python -m pytest
        continue-on-error: true

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       - name: Initialize CodeQL
#         uses: github/codeql-action/init@v3
#         with:
#           languages: python
#           build-mode: none
# 
#       - name: Perform CodeQL Analysis
#         uses: github/codeql-action/analyze@v3

      - name: Build Docker image
        run: |
          docker build \
          -t ${{ secrets.ACR_LOGIN_SERVER }}/shoppingassistantservice:${{ github.sha }} \
          -t ${{ secrets.ACR_LOGIN_SERVER }}/shoppingassistantservice:latest \
          ./services/shoppingassistantservice

#       - name: Scan image for vulnerabilities
#         uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
#         with:
#           image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/shoppingassistantservice:${{ github.sha }}
#           format: table
#           exit-code: '1'
#           ignore-unfixed: true
#           severity: CRITICAL

      - name: Push image to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/shoppingassistantservice --all-tags
